-- Create LEADS table to store quote requests
create table public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  full_name text not null,
  email text not null,
  phone text not null,
  fiscal_code text,
  customer_type text check (customer_type in ('Privato', 'P.IVA')),
  message text,
  vehicle_id uuid references public.veicoli(id), -- Changed to UUID to match veicoli table
  vehicle_snapshot jsonb, -- Stores vehicle title/price at time of request
  configuration jsonb,    -- Stores selected duration, km, color, etc.
  status text default 'new' check (status in ('new', 'contacted', 'converted', 'closed'))
);

-- Enable RLS
alter table public.leads enable row level security;

-- Policy: Allow anyone (anon) to INSERT a new lead (public form)
create policy "Allow public to insert leads"
on public.leads for insert
to anon, authenticated
with check (true);

-- Policy: Allow admins (service_role) to READ all leads
create policy "Allow admins to view leads"
on public.leads for select
to service_role
using (true);
