-- DSAS Mobility Database Structure (Supabase / PostgreSQL)

-- 1. LOOKUP TABLES (Mini-tablas)

-- Marca (Brands)
CREATE TABLE brands (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Categoria (Categories)
CREATE TABLE categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Alimentazione (Fuel Types)
CREATE TABLE fuel_types (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Cambio (Transmissions)
CREATE TABLE transmissions (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tempo di consegna (Delivery Times)
CREATE TABLE delivery_times (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. MAIN TABLE (Vehicles / Posts)

CREATE TABLE vehicles (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Core Identification
  title text not null, -- "Titolo"
  slug text not null unique, -- "Slug" (Auto-generated in app)
  sku text not null unique, -- "SKU" (Auto-generated in app)
  
  -- Relationships (Foreign Keys)
  brand_id bigint references brands(id), -- "Marca"
  category_id bigint references categories(id), -- "Categoria"
  fuel_type_id bigint references fuel_types(id), -- "Alimentazione"
  transmission_id bigint references transmissions(id), -- "Cambio"
  delivery_time_id bigint references delivery_times(id), -- "Tempo di consegna"
  
  -- Detailed Info
  model text not null, -- "Modello"
  version text, -- "Versione"
  promo boolean default false, -- "Promo" (Switch)
  image_url text not null, -- "Foto del Veicolo" (URL)
  
  -- Long Term Rental Data (Standard Fields)
  monthly_price numeric, -- "Canone mensile"
  duration_months integer, -- "Durata mesi"
  advance_payment numeric, -- "Anticipo"
  annual_km integer, -- "Km annui"
  
  -- Short Term Option ("Breve")
  is_short_term boolean default false, -- Switch "Breve" (Si/No)
  
  -- Short Term Specific Fields (Only used if is_short_term = true)
  daily_price numeric, -- "Prezzo Giornaliero"
  daily_km integer, -- "Km Giornaliero"
  weekly_price numeric, -- "Prezzo Settimanale"
  weekly_km integer, -- "Km Settimanale"
  monthly_short_price numeric, -- "Prezzo Mensile" (distinct from long term)
  monthly_short_km integer, -- "Km Mensile"
  deposit numeric, -- "Cauzione richiesta"
  extra_km_cost numeric -- "Costo per chilometro"
);

-- 3. INITIAL DATA SEEDING (Datos Iniciales)

-- Brands
INSERT INTO brands (name) VALUES 
('ALFA'), ('AUDI'), ('BDY'), ('BMW'), ('BYD'), ('CITROEN'), ('CUPRA'), ('DACIA'), ('DS'), ('FIAT'), 
('FORD'), ('HONDA'), ('HYUNDAI'), ('JEEP'), ('KIA'), ('LANCIA'), ('LAND'), ('MASERATI'), 
('MERCEDES-BENZ'), ('MG'), ('NISSAN'), ('OPEL'), ('PEUGEOT'), ('POLESTAR'), ('PORSCHE'), 
('RENAULT'), ('SEAT'), ('SKODA'), ('SUZUKI'), ('TESLA'), ('TOYOTA'), ('VOLKSWAGEN'), ('VOLVO');

-- Categories
INSERT INTO categories (name) VALUES 
('Berlina'), ('City Car'), ('Station Wagon'), ('SUV / Crossover'), ('Veicoli commerciali'), 
('Cabrio'), ('Coupé'), ('Monovolume'), ('Pick-up'), ('Roadster'), ('Fuoristrada'), ('Elettrica');

-- Fuel Types
INSERT INTO fuel_types (name) VALUES 
('Benzina'), ('Diesel'), ('Elettrica'), ('Ibrida-Benzina'), ('Ibrida-Diesel');

-- Transmissions
INSERT INTO transmissions (name) VALUES 
('Manuale'), ('Automatico');

-- Delivery Times
INSERT INTO delivery_times (name) VALUES 
('Garanzia di Mobilità'), ('Pronta Consegna'), ('Veicolo pre-ordinato');
