-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. TABLES FOR DROPDOWNS (Lookup Tables)
-- We creaate them to have a source of truth, but we can also just store text in the main table for simplicity as requested.
-- However, creating them allows for easy management of options later.

-- MARCHE
create table public.marche (
  id bigint generated by default as identity primary key,
  nome text unique not null
);

insert into public.marche (nome) values 
('ALFA'), ('AUDI'), ('BDY'), ('BMW'), ('BYD'), ('CITROEN'), ('CUPRA'), ('DACIA'), ('DS'), ('FIAT'), 
('FORD'), ('HONDA'), ('HYUNDAI'), ('JEEP'), ('KIA'), ('LANCIA'), ('LAND'), ('MASERATI'), ('MERCEDES-BENZ'), 
('MG'), ('NISSAN'), ('OPEL'), ('PEUGEOT'), ('POLESTAR'), ('PORSCHE'), ('RENAULT'), ('SEAT'), ('SKODA'), 
('SUZUKI'), ('TESLA'), ('TOYOTA'), ('VOLKSWAGEN'), ('VOLVO');

-- CATEGORIE
create table public.categorie (
  id bigint generated by default as identity primary key,
  nome text unique not null
);

insert into public.categorie (nome) values 
('Berlina'), ('City Car'), ('Station Wagon'), ('SUV / Crossover'), ('Veicoli commerciali'), 
('Cabrio'), ('Coupé'), ('Monovolume'), ('Pick-up'), ('Roadster'), ('Fuoristrada'), ('Elettrica');

-- ALIMENTAZIONI
create table public.alimentazioni (
  id bigint generated by default as identity primary key,
  nome text unique not null
);

insert into public.alimentazioni (nome) values 
('Benzina'), ('Diesel'), ('Elettrica'), ('Ibrida-Benzina'), ('Ibrida-Diesel');

-- CAMBI
create table public.cambi (
  id bigint generated by default as identity primary key,
  nome text unique not null
);

insert into public.cambi (nome) values 
('Manuale'), ('Automatico');

-- TEMPI CONSEGNA
create table public.tempi_consegna (
  id bigint generated by default as identity primary key,
  nome text unique not null
);

insert into public.tempi_consegna (nome) values 
('Garanzia di Mobilità'), ('Pronta Consegna'), ('Veicolo pre-ordinato');


-- 2. MAIN TABLE: VEICOLI
create table public.veicoli (
  id uuid default uuid_generate_v4() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Core Fields
  titolo text not null,
  marca text not null, -- Storing text for simplicity as per request "mini wordpress", but could be FK
  modello text not null,
  versione text,
  categoria text not null,
  
  -- System Fields
  slug text unique not null,
  sku text unique not null,
  
  -- Media
  immagine_url text, -- Main image
  
  -- Technical Specs
  alimentazione text,
  cambio text,
  
  -- Offer Details
  promo boolean default false, -- For "NUOVE OFFERTE DEL MESE"
  tempo_consegna text,
  
  -- Long Term Rental Data
  canone_mensile numeric,
  anticipo numeric,
  durata_mesi integer,
  km_annui integer,
  
  -- Short Term Rental Data (Optional)
  noleggio_breve boolean default false,
  
  prezzo_giornaliero numeric,
  km_giornaliero integer,
  
  prezzo_settimanale numeric,
  km_settimanale integer,
  
  prezzo_mensile_breve numeric,
  km_mensile_breve integer,
  
  cauzione_richiesta numeric,
  costo_per_km numeric
);

-- 3. SECURITY POLICIES (RLS)
alter table public.veicoli enable row level security;
alter table public.marche enable row level security;
alter table public.categorie enable row level security;
alter table public.alimentazioni enable row level security;
alter table public.cambi enable row level security;
alter table public.tempi_consegna enable row level security;

-- Allow read access to everyone
create policy "Public Read Veicoli" on public.veicoli for select using (true);
create policy "Public Read Marche" on public.marche for select using (true);
create policy "Public Read Categorie" on public.categorie for select using (true);
create policy "Public Read Alimentazioni" on public.alimentazioni for select using (true);
create policy "Public Read Cambi" on public.cambi for select using (true);
create policy "Public Read Tempi" on public.tempi_consegna for select using (true);

-- Allow insert/update/delete ONLY for authenticated users (or service role)
-- Note: 'anon' key users are technically authenticated but as role 'anon'. 
-- If you want ONLY logged in admins to edit, use 'authenticated' role requirements.
-- For now, allowing all 'anon' to insert for simplicity of testing from the frontend provided 
-- NO AUTH SYSTEM is yet in place for users. If there is an admin login, we restrict this.
-- Assuming the admin panel usage implies trusted access for now or development mode.
-- Updated to allow Anon insert for testing:
create policy "Enable insert for anon/authenticated" on public.veicoli for insert with check (true);
create policy "Enable update for anon/authenticated" on public.veicoli for update using (true);
create policy "Enable delete for anon/authenticated" on public.veicoli for delete using (true);
